### ISSUE TITLE
can use it with storyboard?

### ISSUE THREAD

**Issue by ihomam** [applidium/ADTransitionController#1]
how to use this controller with storyboard??

**Comment by nderkach** [comment]
I made it work with storyboards, although it wasn't easy.
Here is how you do it (this example uses a standalone transition delegate as inheritage was not possible) :

* Init your destination view controller (DestinationViewController) from the storyboard and push it manually, rather than through a segue:

        DestinationViewController *vc = [[UIStoryboard storyboardWithName:@"Main" bundle:nil] instantiateViewControllerWithIdentifier:@"ChatViewController"];
        ADTransition *transition = [[ADGlueTransition alloc] initWithDuration:.5f orientation:ADTransitionRightToLeft sourceRect:self.view.frame];
        ADTransitioningDelegate* transitioningDelegate = [[ADTransitioningDelegate alloc] initWithTransition:transition];
        vc.transitioningDelegate = transitioningDelegate;
        [self.navigationController pushViewController:vc animated:YES];

That should do the trick.
